{#-
Below are imports for Bakery's macros. If any are unneeded, they can be removed.
Bakery handles bootstrapping the files into template rendering.
-#}
{%- import "apt.j2" as apt -%}
{%- import "python.j2" as python -%}
{%- import "quarto.j2" as quarto -%}
{%- import "r.j2" as r -%}

# Build Python using uv in a separate stage
{{ python.build_stage(Dependencies.python) }}

FROM docker.io/library/ubuntu:24.04 AS build
LABEL org.opencontainers.image.base.name="docker.io/library/ubuntu:24.04"

### ARG declarations ###
ARG DEBIAN_FRONTEND=noninteractive
ARG WORKBENCH_VERSION="{{ Image.Version }}"
ARG RSTUDIO_INSTALL_NO_LICENSE_INITIALIZATION=1

ENV STARTUP_DEBUG_MODE=0
ENV PWB_LICENSE=""
ENV PWB_LICENSE_SERVER=""
ENV USER_NAME="azureuser"
ENV USER_PASSWORD=""
ENV PUID=1001
ENV PGID=1001
ENV PWB_LAUNCHER=true
ENV PWB_LAUNCHER_TIMEOUT=10
ENV DIAGNOSTIC_DIR=/var/log/rstudio
ENV DIAGNOSTIC_ENABLE=false
ENV DIAGNOSTIC_ONLY=false

COPY --chmod=0644 {{ Path.Version }}/conf/license-manager/TurboActivate.dat /opt/rstudio-license/license-manager.conf

SHELL ["/bin/bash", "-euo", "pipefail", "-c"]

### Remove ubuntu user ###
# Ubuntu 24.04 assigns the uid 1000 to the ubuntu user. This is incompatible with the hardcoded PUID=1000 environment
# variable set by Azure ML. By removing the ubuntu user, we can free up the 1000 uid entirely.
RUN userdel -r ubuntu

### Setup environment ###
{{ apt.run_setup() }}

## Install Apt Packages ###
{% if not Image.Variant == "Minimal" -%}
COPY {{ Path.Version }}/deps/apt_packages.txt /tmp/packages.txt
COPY {{ Path.Version }}/deps/optional_apt_packages.txt /tmp/optional_packages.txt
{{ apt.run_install(files = ['/tmp/packages.txt', '/tmp/optional_packages.txt']) }} && \
    rm -f /tmp/packages.txt /tmp/optional_packages.txt
{% else -%}
COPY {{ Path.Version }}/deps/apt_packages.txt /tmp/packages.txt
{{ apt.run_install(files = ['/tmp/packages.txt']) }} && \
    rm -f /tmp/packages.txt
{%- endif %}

### Install wait-for-it ###
COPY --chmod=0755 {{ Path.Image }}/scripts/wait-for-it.sh /usr/local/bin/wait-for-it.sh

RUN curl -fsSL https://aka.ms/InstallAzureCLIDeb | bash \
    && az extension add -n ml -y

### Install Workbench {{ Image.Version }} ###
COPY --chmod=0755 {{ Path.Version }}/scripts/install_workbench.sh /tmp/install_workbench.sh
{% set monitor_version = "${WORKBENCH_VERSION//+/-}" %}
RUN {% if Image.DownloadURL is defined %}DOWNLOAD_URL="{{ Image.DownloadURL }}" {% endif %}\
    /tmp/install_workbench.sh && \
    rm -f /tmp/install_workbench.sh && \
    echo "RSPM={{ r.get_p3m_cran_repo(Image.OS) }}" > /etc/rstudio/repos.conf && \
    echo "CRAN={{ r.get_p3m_cran_repo(Image.OS) }}" >> /etc/rstudio/repos.conf && \
    mkdir -p /opt/rstudio-license/ && \
    mkdir -p /var/lib/rstudio-workbench/ && \
    curl -fsSL "https://s3.amazonaws.com/rstudio-ide-build/monitor/jammy/rsp-monitor-workbench-azureml-amd64-{{ monitor_version }}.tar.gz" \
    | tar xzvf - --strip 2 -C /opt/rstudio-license/ && \
    chmod 0755 /opt/rstudio-license/license-manager && \
    mv /opt/rstudio-license/license-manager /opt/rstudio-license/license-manager-orig && \
    rm -f /usr/lib/rstudio-server/bin/license-manager

### Install Quarto to PATH ###
RUN ln -s /lib/rstudio-server/bin/quarto/bin/quarto /usr/local/bin/quarto

{% if not Image.Variant == "Minimal" -%}
### Install Pro Drivers ###
{{ apt.run_install(packages="rstudio-drivers") | indent(4) }}

### Install Python from previous stage ###
{{ python.copy_from_build_stage() }}

### Install R ###
{{ r.run_install(Dependencies.R) }}

### Install Jupyter ###
{{ python.run_install_jupyterlab_workbench(Dependencies.python.0, jupyterlab_version_pin = "<5", pwb_jupyterlab_version_pin = "<2") }}

### Install Jupyter kernels ###
{% for python_version in Dependencies.python -%}
RUN {{ python.install_packages(python_version, "ipykernel") }} && \
    {{ python.get_version_directory(python_version) }}/bin/python -m ipykernel install --user --name python{{ python_version }} --display-name "Python {{ python_version }}"

{% endfor -%}
### Install Python Packages ###
COPY {{ Path.Version }}/deps/py_packages.txt /tmp/py_packages.txt
{{ python.run_install_packages(Dependencies.python, requirements_file = ['/tmp/py_packages.txt']) }} && \
    rm -f /tmp/py_packages.txt && \
{{ python.symlink_version(Dependencies.python.0, "/opt/python/default") | indent(4) }}

### Install R Packages ###
COPY {{ Path.Version }}/deps/r_packages.txt /tmp/r_packages.txt
{{ r.run_install_packages(Dependencies.R, package_list_files = ['/tmp/r_packages.txt'], _os = Image.OS) }} && \
    rm -f /tmp/r_packages.txt
{%- endif %}

### Copy startup scripts and configuration files ###
COPY --chmod=0755 "{{ Path.Version }}/conf/license-manager/license-manager-shim" /opt/rstudio-license/license-manager
COPY --chmod=0775 "{{ Path.Version }}/scripts/startup.sh" /usr/local/bin/startup.sh
COPY "{{ Path.Version }}/conf/supervisor/supervisord.conf" /etc/supervisor/supervisord.conf
COPY "{{ Path.Version }}/conf/supervisor/startup" /startup/base
COPY "{{ Path.Version }}/conf/supervisor/startup-launcher" /startup/launcher
COPY "{{ Path.Version }}/conf/jupyter/*" "{{ Path.Version }}/conf/launcher/*" "{{ Path.Version }}/conf/rstudio/*" "{{ Path.Version }}/conf/positron/*" "{{ Path.Version }}/conf/vscode/*" /etc/rstudio/
COPY "{{ Path.Version }}/web/landing/*" /usr/lib/rstudio-server/www/

{%- if Image.Variant != "Minimal" %}

### Install TinyTeX using Quarto ###
# Caches won't invalidate correctly on new releases for TinyTeX installs. This ADD instruction is a workaround to bust
# the cache on new releases.
ADD https://github.com/rstudio/tinytex-releases/releases/latest /tmp/tinytex-release.json
RUN {{ quarto.install_tinytex_command("/lib/rstudio-server/bin/quarto/bin/quarto", update_path=True, home_path="/opt") }} \
    && rm -f /tmp/tinytex-release.json
{%- endif %}

EXPOSE 8787/tcp
EXPOSE 5559/tcp

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]

FROM build AS clamav

SHELL ["/bin/bash", "-euo", "pipefail", "-c"]

# Set up ClamAV
{{ apt.run_install("clamav") }}

# Update ClamAV
RUN freshclam --log="/var/log/clamav/clamupdate.log"

# Scan all but /sys for viruses. If this fails, the Docker build will fail.
#
# --exclude options are false positives per rstudio/rstudio-docker-products#704.
# They can likely be removed in the future after ClamAV's database is updated.
RUN clamscan \
    --recursive \
    --infected \
    --exclude-dir="^/sys" \
    --exclude="/opt/az/lib/python[0-9.]+/ensurepip/_bundled/pip-[0-9.]+-py3-none-any.whl" \
    --exclude="/opt/az/lib/python[0-9.]+site-packages/pip/_vendor/distlib/w32.exe" \
    --exclude="/opt/az/lib/python[0-9.]+/site-packages/pip/_vendor/distlib/w64-arm.exe" \
    --exclude="/opt/az/lib/python[0-9.]+/site-packages/pip/_vendor/distlib/t64-arm.exe" \
    --log "/var/log/clamav/clamscan.log" /

# Ignore the intermediate 'clamav' multi-stage build step so we don't distribute
# with ClamAV installed. Avoid adding changes in this stage unless they are related
# to the ClamAV stage. Since the ClamAV stage may be cached, you can't guarantee
# another full scan if you change anything beyond this point.
FROM build AS final

# Copy ClamAV scan logs so the end user can see them.
COPY --from=clamav /var/log/clamav/clamscan.log /var/log/clamav/clamupdate.log /

LABEL azure.ii.language='en-US' \
      azure.ii.support.stage='preview' \
      azure.ii.privacy='{"tracking":false,"ads":false,"network-traffic":true}' \
      azure.ii.auth='{"disable":"DISABLE_AUTH"}' \
      azure.ii.user='{"mode":"entry_point","name":"USER_NAME","uid":"PUID","gid":"PGID"}' \
      azure.ii.locale='{"tz":"TZ","lang":"LANG"}' \
      azure.ii.endpoints='[{"label":"connect","target":8787,"protocol":"http"}]'
